git:
  submodules: false
before_install:
  - gem install scan
language: objective-c
osx_image: xcode7.3
matrix:
  include:
    - install: carthage bootstrap --use-submodules --no-use-binaries --platform iOS
      script: scan --scheme RxAdvancedNimble-iOS
      env: JOB=iOS
    - install: carthage bootstrap --use-submodules --no-use-binaries --platform mac
      script: scan --scheme RxAdvancedNimble-macOS
      env: JOB=macOS
    - install: carthage bootstrap --use-submodules --no-use-binaries --platform tvOS
      script: scan --scheme RxAdvancedNimble-tvOS
      env: JOB=tvOS
